# Generated by Django 6.0.7 on 2026-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('binan', 'Binan'), ('nuvali', 'Nuvali'), ('santa_rosa_city', 'Santa Rosa City')], default='binan', help_text='Which area this leader is assigned to for discipling students.', max_length=20),
        ),
    ]
