# Generated by Django 6.0.7 on 2026-08-13 05:54

import django.db.models.deletion
from django.db import migrations, models


def reassign_student_youth_to_college(apps, schema_editor):
    """
    'student_youth' is being split into 'high_school' and 'college'.
    Since we can't know which one an existing leader actually is, they're
    moved to 'college' as a reasonable default (not a deletion) -- staff
    should review and correct via that leader's Edit Profile afterward.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(demography='student_youth').update(demography='college')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_area'),
        ('members', '0005_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.RunPython(reassign_student_youth_to_college, noop_reverse),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Whether this leader is currently a student.'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Required if is_student is set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leaders', to='members.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_level',
            field=models.CharField(blank=True, choices=[('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('college_1', '1st Year College'), ('college_2', '2nd Year College'), ('college_3', '3rd Year College'), ('college_4', '4th Year College'), ('college_5_plus', '5th+ Year College')], help_text='Required if is_student is set.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='demography',
            field=models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('single_young_professional', 'Single / Young Professional'), ('married', 'Married'), ('parent', 'Parent'), ('senior', 'Senior')], max_length=30),
        ),
    ]
