# Generated by Django 6.0.7 on 2026-08-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_student_user_school_user_year_level_and_more'),
        ('members', '0005_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Required when demography is High School or College.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_leaders', to='members.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_level',
            field=models.CharField(blank=True, choices=[('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('college_1', '1st Year College'), ('college_2', '2nd Year College'), ('college_3', '3rd Year College'), ('college_4', '4th Year College'), ('college_5_plus', '5th+ Year College')], help_text='Required when demography is High School or College.', max_length=20),
        ),
    ]
