# Generated by Django 6.1 on 2026-08-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='demography',
            field=models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('mixed', 'Mixed'), ('others', 'Others')], default='mixed', help_text='What kind of group this is, demographically.', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='demography_other',
            field=models.CharField(blank=True, help_text="Required when demography is 'Others' -- describe it.", max_length=100),
        ),
    ]
