# Generated by Django 6.0.7 on 2026-07-29 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order in the journey sequence.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'ministries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('year_level', models.CharField(choices=[('elementary', 'Elementary'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12'), ('college_1', '1st Year College'), ('college_2', '2nd Year College'), ('college_3', '3rd Year College'), ('college_4', '4th Year College'), ('college_5_plus', '5th+ Year College'), ('out_of_school', 'Out of School'), ('adult', 'Adult')], max_length=20)),
                ('is_in_ministry', models.BooleanField(default=False, help_text='Whether this member is also serving within the ministry.')),
                ('remarks', models.TextField(blank=True, help_text='An encouraging note or story about this member, from their leader.')),
                ('remarks_photo', models.ImageField(blank=True, null=True, upload_to='member_remarks/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='member_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discipleship_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.discipleshipstage')),
                ('ministries', models.ManyToManyField(blank=True, help_text='Which ministry team(s) this member serves in, if any.', related_name='members', to='members.ministry')),
                ('school', models.ForeignKey(help_text="Use an 'N/A' school entry for members who aren't students.", on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_group', models.CharField(choices=[('member', 'Member'), ('intern', 'Intern'), ('leader', 'Leader')], max_length=10)),
                ('attendance_status', models.CharField(choices=[('new', 'New (joined this month)'), ('active', 'Active (attended at least once this month)'), ('inactive', 'Inactive (no attendance this month)')], max_length=10)),
                ('date_joined_group', models.DateField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member')),
            ],
            options={
                'ordering': ['member__last_name', 'member__first_name'],
                'unique_together': {('group', 'member')},
            },
        ),
    ]
