# Generated by Django 6.0.7 on 2026-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='role_in_group',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('intern', 'Intern'), ('leader', 'Leader')], default='member', help_text='Whether this person is a regular member, an intern, or a leader. This applies to them overall, not per-group (e.g. leadership group members are usually tagged Leader or Intern here).', max_length=10),
        ),
    ]
