# Generated by Django 6.0.7 on 2026-08-08 14:59

from django.db import migrations, models


def reassign_leader_role_to_intern(apps, schema_editor):
    """
    Any existing Member profile tagged 'leader' gets moved to 'intern'
    instead, since 'leader' is being retired as a Member-profile role --
    those people should have a Leader account instead. This is a safe
    default, not a deletion; staff can review and adjust afterward via
    the Members list (filter isn't available for this anymore, but the
    affected people were previously visible under role=leader).
    """
    Member = apps.get_model('members', 'Member')
    Member.objects.filter(role='leader').update(role='intern')


def noop_reverse(apps, schema_editor):
    # Deliberately not reversible -- we don't know which 'intern' rows
    # used to be 'leader', so there's nothing safe to restore.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_groupmembership_role_in_group_member_role'),
    ]

    operations = [
        migrations.RunPython(reassign_leader_role_to_intern, noop_reverse),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('intern', 'Intern')], default='member', help_text="Whether this person is a regular member or an intern being developed. People who are already Leaders have their own Leader account instead of a Member profile, so 'Leader' isn't an option here.", max_length=10),
        ),
    ]
