# Generated by Django 6.0.7 on 2026-08-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
    ]
