# Generated by Django 6.0.7 on 2026-08-10 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('members', '0004_remove_member_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['member__last_name', 'member__first_name', 'leader__last_name', 'leader__first_name']},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'member')},
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='leader',
            field=models.ForeignKey(blank=True, help_text="Set this instead of 'member' when the person being added already has a Leader account.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='members.member'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'leader'), ('group', 'member')},
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('leader__isnull', True), ('member__isnull', False)), models.Q(('leader__isnull', False), ('member__isnull', True)), _connector='OR'), name='groupmembership_exactly_one_of_member_or_leader'),
        ),
    ]
