# Generated by Django 6.1 on 2026-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='area',
            field=models.CharField(choices=[('binan', 'Binan'), ('nuvali', 'Nuvali'), ('santa_rosa_city', 'Santa Rosa City')], default='binan', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='demography',
            field=models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('mixed', 'Mixed'), ('others', 'Others')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='demography_other',
            field=models.CharField(blank=True, help_text="Required when demography is 'Others' -- describe it.", max_length=100),
        ),
    ]
