# Generated by Django 6.1 on 2026-08-24 10:19

from django.db import migrations, models


def fold_demography_other_into_demography(apps, schema_editor):
    """
    Before dropping demography_other, copy its text into demography for
    any school where demography was 'others' -- otherwise that school's
    actual description (e.g. "Vocational Institute") would be lost,
    leaving just the literal word "others" behind.
    """
    School = apps.get_model('members', 'School')
    for school in School.objects.filter(demography='others').exclude(demography_other=''):
        school.demography = school.demography_other
        school.save(update_fields=['demography'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_school_area_school_demography_and_more'),
    ]

    operations = [
        migrations.RunPython(fold_demography_other_into_demography, noop_reverse),
        migrations.RemoveField(
            model_name='school',
            name='demography_other',
        ),
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.CharField(blank=True, help_text="Free text -- e.g. 'Nuvali', 'Santa Rosa City'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='demography',
            field=models.CharField(blank=True, help_text="Free text -- e.g. 'College', 'High School', 'Mixed'.", max_length=100),
        ),
    ]
