# Generated by Django 6.1 on 2026-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_school_demography_other_alter_school_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_doing_one_on_one',
            field=models.BooleanField(default=False, help_text='Whether this person is currently doing a One2One discipleship meeting with someone.'),
        ),
        migrations.AddField(
            model_name='member',
            name='one_on_one_with',
            field=models.CharField(blank=True, help_text="Name of who they're doing One2One with. Required if is_doing_one_on_one is set.", max_length=150),
        ),
    ]
