# Generated by Django 6.1 on 2026-08-29 22:43

from django.db import migrations


def add_others_school(apps, schema_editor):
    """
    Seeds a catch-all 'Others' school entry, meant for students who are
    Home Schooled or in Elementary (not tied to a specific named
    institution). Safe to run more than once (get_or_create).
    """
    School = apps.get_model('members', 'School')
    School.objects.get_or_create(
        name="Others",
        defaults={"area": "", "demography": "Home Schooled / Elementary"},
    )


def remove_others_school(apps, schema_editor):
    School = apps.get_model('members', 'School')
    School.objects.filter(name="Others").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_is_doing_one_on_one_member_one_on_one_with'),
    ]

    operations = [
        migrations.RunPython(add_others_school, remove_others_school),
    ]
